### ISSUE TITLE
Add support to pyrra helm chart for webhook validation

### ISSUE THREAD

**Issue by sepulworld** [rlex/helm-charts#145]
Would be great to add support for webhook validation. 

https://github.com/pyrra-dev/pyrra/tree/main?tab=readme-ov-file#applying-yaml-and-validating-webhooks-via-cert-manager

If there is a prerequiste that cert-manager is available, we could have a flag that would deploy Certificate, Issuer, and ValidatingWebhookConfiguration

Also, enable flag in Deployment and define and attach volume for self-signed cert.

May I submit an MR for this?

**Comment by rlex** [comment]
I think it can be done. I actually did something similar in another chart, which doesn't require cert-manager for certs: https://github.com/rlex/helm-charts/tree/master/charts/runtimeclass-controller

But if pyrra ones are made in such way that it absolutely requires cert-manager, a simple if condition in templates should work.

**Comment by sepulworld** [comment]
Sounds good. i put in a PR and added a comment. If you have a chance to check out.

**Comment by sebastiangaiser** [comment]
@rlex @sepulworld this is done, isn't it?

**Comment by sepulworld** [comment]
Yep! Thank you! Works as intended!
